/**
 * Tier B — host harness end to end (EB-HB-1..9).
 *
 * Runs the real `scripts/install-harness.sh --all` into a scratch HOME and
 * grades the result with `scripts/verify-harness-install.ts --json`. Nothing is
 * mocked: the installers, the artifact bundles, the MCP registration and the
 * state file are all the shipping ones.
 *
 * THREE THINGS THIS FILE DELIBERATELY DOES NOT DO.
 *
 * 1. It never asserts on `install-harness.sh`'s exit code. The installer's
 *    plugin phase acts only on DETECTED hosts (install-harness.sh:250-282 via
 *    `installer_host_detected`, installer-shared.sh:225-241), so on a machine
 *    missing a host CLI the exit code moves for a reason unrelated to the code
 *    under test. Every verdict here comes from the oracle's per-host JSON.
 *
 * 2. It does not let host detection depend on the machine. Detection is
 *    "config dir exists under HOME **or** a binary is on PATH", and under a
 *    scratch HOME the directory probe never fires — so on a dev box detection
 *    collapses to `command -v` and finds three or four hosts, while CI finds
 *    zero, and the same assertion inverts between them. This file therefore
 *    SEEDS the four config directories, the strategy
 *    `scripts/tests/test-install-harness-cli.sh:62-65` uses and for the same
 *    reason. (The other established strategy, scrubbing PATH — see
 *    `test-plugin-auto-install.sh:6-9` — is used below for the negative case,
 *    where the goal is the opposite: no host detected at all.)
 *
 * 3. It does not regenerate the plugin bundles. `install-harness.sh:197-204`
 *    normally runs both generators against `$REPO_ROOT` on every non-dry run,
 *    writing ~5 MB into the worktree the test is running in — and then any
 *    `generate:artifacts --check` in the same suite would be reading output
 *    this test had just produced. `MASSA_AI_SKIP_ARTIFACT_GENERATION=1` turns
 *    that off, and the guard below fails loudly if the bundles are absent
 *    rather than letting the install quietly produce an empty result.
 */

import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import fs from "fs";
import os from "os";
import path from "path";

const REPO_ROOT = path.resolve(import.meta.dir, "..", "..");
const HOSTS = ["claude", "codex", "cursor", "opencode"] as const;
const ARTIFACTS = ["mcp", "plugin", "hooks", "skills", "commands", "subagents"] as const;

/** Config directory each host is detected by, mirroring installer_host_config_dir. */
const HOST_CONFIG_DIRS: Record<string, string> = {
  claude: ".claude",
  codex: ".codex",
  cursor: ".cursor",
  opencode: path.join(".config", "opencode"),
};

interface Row {
  host: string;
  artifact: string;
  status: "ok" | "missing" | "partial" | "n/a";
  detail: string;
  detected: boolean;
}

const scratchDirs: string[] = [];

function scratchHome(opts: { seedConfigDirs: boolean }): string {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "massa-ai-harness-e2e-"));
  scratchDirs.push(home);
  if (opts.seedConfigDirs) {
    for (const host of HOSTS) {
      fs.mkdirSync(path.join(home, HOST_CONFIG_DIRS[host]!), { recursive: true });
    }
  }
  return home;
}

/** Run the oracle against a scratch home and parse its rows. */
function oracle(home: string, extraEnv: Record<string, string> = {}): { rows: Row[]; exitCode: number } {
  const proc = Bun.spawnSync({
    cmd: ["bun", "scripts/verify-harness-install.ts", "--home", home, "--json"],
    cwd: REPO_ROOT,
    env: { ...process.env, ...extraEnv },
    stdout: "pipe",
    stderr: "pipe",
  });
  return { rows: JSON.parse(proc.stdout.toString()) as Row[], exitCode: proc.exitCode ?? -1 };
}

function statusFor(rows: Row[], host: string, artifact: string): string {
  return rows.find((r) => r.host === host && r.artifact === artifact)?.status ?? "<absent>";
}

/** A PATH with bun reachable but no host CLI, so detection can only come from a config dir. */
function scrubbedPath(): string {
  const bunDir = path.dirname(Bun.which("bun") ?? "/usr/bin/bun");
  return `${bunDir}:/usr/bin:/bin`;
}

// ── The one shared install ───────────────────────────────────────────────────
// install-harness.sh --all is the expensive step, so every EB-HB case that
// grades a completed install reads this one result rather than re-running it.

let installedHome = "";
let installExitCode = -1;
let installedRows: Row[] = [];

beforeAll(() => {
  // Fail loudly and by name rather than measuring an empty install: the
  // bundles are gitignored build output (AD-016), regenerated by
  // `pretest:scripts` for `bun run test:scripts` but NOT by a direct
  // `bun test <file>` run.
  const bundleProbe = path.join(REPO_ROOT, "apps", "claude-plugin", "skills", "massa-ai", "SKILL.md");
  if (!fs.existsSync(bundleProbe)) {
    throw new Error(
      `Generated plugin bundles are absent (${bundleProbe}). Run \`bun run generate:artifacts\` first.`,
    );
  }

  installedHome = scratchHome({ seedConfigDirs: true });
  const proc = Bun.spawnSync({
    cmd: ["bash", "scripts/install-harness.sh", "--all", "--target", installedHome, "--yes"],
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      HOME: installedHome,
      MASSA_AI_SKIP_ARTIFACT_GENERATION: "1",
    },
    stdout: "pipe",
    stderr: "pipe",
  });
  installExitCode = proc.exitCode ?? -1;
  installedRows = oracle(installedHome).rows;
}, 300_000);

afterAll(() => {
  for (const dir of scratchDirs) fs.rmSync(dir, { recursive: true, force: true });
});

describe("EB-HB-1..3 — the oracle's shape is stable", () => {
  test("emits exactly one row per host per artifact", () => {
    expect(installedRows).toHaveLength(HOSTS.length * ARTIFACTS.length);
    for (const host of HOSTS) {
      const forHost = installedRows.filter((r) => r.host === host);
      expect(forHost.map((r) => r.artifact).sort()).toEqual([...ARTIFACTS].sort());
    }
  });

  test("every row carries a detection verdict", () => {
    for (const row of installedRows) {
      expect(typeof row.detected).toBe("boolean");
    }
  });

  test("a seeded config directory is enough to detect a host, with no CLI on PATH", () => {
    // The property that makes this suite portable: with PATH scrubbed of every
    // host CLI, detection still finds all four, because the directories were
    // seeded. Without it, this file would assert four hosts here and zero in
    // CI from identical source.
    const { rows } = oracle(installedHome, { PATH: scrubbedPath() });
    for (const host of HOSTS) {
      const row = rows.find((r) => r.host === host)!;
      expect(row.detected).toBe(true);
    }
  });
});

describe("EB-HB-4..7 — install-harness.sh --all installs every detected host", () => {
  test("all four hosts are detected in the install target", () => {
    for (const host of HOSTS) {
      const row = installedRows.find((r) => r.host === host)!;
      expect(row.detected).toBe(true);
    }
  });

  test.each([...HOSTS])("%s has every artifact installed", (host) => {
    // Per host, per artifact, line by line — never a single aggregate, and
    // never the installer's exit code.
    for (const artifact of ARTIFACTS) {
      expect(`${host}/${artifact}=${statusFor(installedRows, host, artifact)}`).toBe(
        `${host}/${artifact}=ok`,
      );
    }
  });

  test("the oracle agrees with itself: no missing or partial row survives", () => {
    const bad = installedRows.filter((r) => r.status === "missing" || r.status === "partial");
    expect(bad.map((r) => `${r.host}/${r.artifact}:${r.status}`)).toEqual([]);
  });

  test("the installer's own exit code is recorded but never the verdict", () => {
    // Recorded so a future reader can see it, asserted only as "it ran".
    // install-harness.sh:250-282 skips undetected hosts, so on a machine
    // without a host CLI this value moves for reasons unrelated to the code
    // under test — which is exactly why every case above reads the JSON.
    expect(installExitCode).toBeGreaterThanOrEqual(0);
  });
});

describe("EB-HB-8 — an absent host is not a broken install", () => {
  test("no seeded directory and no CLI on PATH reports undetected, not broken", () => {
    // This is the distinction the oracle could not express before it carried
    // `detected`: six `missing` rows for a host that was never installed here
    // looked identical to six `missing` rows for a host whose install failed.
    const bare = scratchHome({ seedConfigDirs: false });
    const { rows } = oracle(bare, { PATH: scrubbedPath() });

    for (const host of HOSTS) {
      const forHost = rows.filter((r) => r.host === host);
      expect(forHost.every((r) => r.detected === false)).toBe(true);
    }
  });

  test("the undetected state is distinguishable from the installed one", () => {
    const bare = scratchHome({ seedConfigDirs: false });
    const { rows } = oracle(bare, { PATH: scrubbedPath() });

    const undetected = rows.filter((r) => r.detected).length;
    const detected = installedRows.filter((r) => r.detected).length;

    expect(undetected).toBe(0);
    expect(detected).toBe(HOSTS.length * ARTIFACTS.length);
  });
});

describe("EB-HB-9 — the installer refuses the real HOME without consent", () => {
  test("a non-interactive run whose target IS $HOME exits 13 and writes nothing", () => {
    // installer_consent_gate (installer-shared.sh:552-575) refuses outright in
    // a non-TTY. The scratch dir stands in for the real $HOME here: the gate
    // compares the target against the live $HOME env var, so making the two
    // equal reproduces the refusal without going anywhere near the developer's
    // own home directory.
    const home = scratchHome({ seedConfigDirs: false });
    const proc = Bun.spawnSync({
      cmd: ["bash", "scripts/install-harness.sh", "--all", "--target", home],
      cwd: REPO_ROOT,
      env: { ...process.env, HOME: home, MASSA_AI_SKIP_ARTIFACT_GENERATION: "1" },
      stdout: "pipe",
      stderr: "pipe",
    });

    expect(proc.exitCode).toBe(13);
    expect(proc.stderr.toString()).toContain("refusing to write real $HOME");
    // Refusal means refusal: the gate runs before any host is touched.
    expect(fs.existsSync(path.join(home, ".config", "massa-ai", "install-state.json"))).toBe(false);
  }, 120_000);
});
