/**
 * Parallel test runner — unit tests (Wave 6 N20, T23-T24)
 *
 * Verifies:
 * - SUITE_TABLE is built correctly with id, description, testFiles, isolationReason, deadlineSensitive
 * - --list-suites flag outputs the table
 * - UNION GUARD: crashed suite = failed (not dropped); result-set ≠ list → exit 1
 * - Per-suite pass/fail/skip counts + total summary
 */

import { describe, test, expect } from "bun:test";
import { spawnSync, type SpawnSyncReturns } from "child_process";
import { writeFileSync, rmSync, existsSync } from "fs";
import path from "path";

const SCRIPT = path.resolve(import.meta.dir, "../run-tests-parallel.ts");

// The runner hardcodes the core package testsRoot as its discovery root:
//   packages/core/src/__tests__
// To exercise a genuinely-crashing suite (DB-dependent tests skip
// gracefully, so DATABASE_URL="" does NOT make them fail), the test
// writes a throwaway .test.ts file DIRECTLY into that testsRoot. The file
// manipulates process.env so the runner classifies it as "process-global
// state" → it gets its own isolated suite (does not pollute pure-shared).
// The filter matches ONLY this file so the rest of the suite roster is
// excluded. Cleanup removes the file afterward.
const CORE_TESTS_ROOT = path.resolve(import.meta.dir, "../../packages/core/src/__tests__");
const CRASH_FILE_NAME = "__zzz_crash_union_guard_probe.test.ts";
const CRASH_FILE_PATH = path.join(CORE_TESTS_ROOT, CRASH_FILE_NAME);

function writeCrashProbe(): void {
  // process.env assignment => classifier returns "process-global state"
  // => isolated suite. process.exit(1) => suite genuinely fails (exit 1).
  writeFileSync(
    CRASH_FILE_PATH,
    [
      `// Auto-generated by run-tests-parallel.test.ts — do NOT commit.`,
      `// Exists only during the UNION GUARD crash probe, then is removed.`,
      `process.env.__CRASH_PROBE = "1";`,
      `import { test } from "bun:test";`,
      `test("crash probe", () => { process.exit(1); });`,
      ``,
    ].join("\n"),
  );
}

function cleanupCrashProbe(): void {
  try {
    if (existsSync(CRASH_FILE_PATH)) rmSync(CRASH_FILE_PATH, { force: true });
  } catch {
    // best-effort
  }
}

function runScript(args: string[], env: Record<string, string> = {}, timeout = 10000): {
  exitCode: number | null;
  stdout: string;
  stderr: string;
} {
  const result: SpawnSyncReturns<string> = spawnSync("bun", ["run", SCRIPT, ...args], {
    encoding: "utf8",
    env: { ...process.env, ...env },
    timeout,
  });
  return {
    exitCode: result.status,
    stdout: result.stdout || "",
    stderr: result.stderr || "",
  };
}

describe("Parallel test runner (T23-T24)", () => {
  test("--list-suites prints SUITE_TABLE with suite entries", () => {
    const result = runScript(["--list-suites"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("SUITE_TABLE");
    expect(result.stdout).toContain("description:");
    expect(result.stdout).toContain("isolationReason:");
    expect(result.stdout).toContain("testFiles:");
    // Should have at least the pure-shared suite
    expect(result.stdout).toContain("pure-shared");
  });

  test("SUITE_TABLE entries have deadlineSensitive marking", () => {
    const result = runScript(["--list-suites"]);
    expect(result.exitCode).toBe(0);
    // At least one suite should be marked DEADLINE-SENSITIVE
    expect(result.stdout).toContain("DEADLINE-SENSITIVE");
  });

  test("SUITE_TABLE has multiple isolation reasons", () => {
    const result = runScript(["--list-suites"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("pure");
    expect(result.stdout).toContain("module mock");
    expect(result.stdout).toContain("database/integration");
    expect(result.stdout).toContain("process-global state");
  });

  test("unknown argument exits with code 2", () => {
    const result = runScript(["--unknown-flag"]);
    expect(result.exitCode).toBe(2);
  });

  test("UNION GUARD: --filter with no matching suites runs 0 suites (no crash)", () => {
    // Filter for a nonexistent suite — should run 0 suites and pass
    const result = runScript(["--filter=NONEXISTENT_SUITE_xyz"]);
    // With 0 suites, the UNION GUARD has nothing to compare → pass
    expect(result.exitCode).toBe(0);
  });

  test("UNION GUARD: SUMMARY is printed with pass/fail counts", () => {
    const result = runScript(["--filter=NONEXISTENT_SUITE_xyz"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("SUMMARY");
    expect(result.stdout).toContain("passed");
    expect(result.stdout).toContain("failed");
  });
});

describe("UNION GUARD crash test (T24)", () => {
  test("deliberately crashing a suite → UNION GUARD fails (exit 1)", () => {
    // Strategy: drop a throwaway crashing test file directly into the core
    // package testsRoot (the runner's hardcoded discovery root). The file
    // manipulates process.env so the classifier tags it "process-global
    // state" → isolated suite (its own entry, does not join pure-shared).
    // The filter matches ONLY this file so the single-suite run exits 1.
    // This kills the "UNION GUARD always passes" mutant and the
    // "crashes are dropped" mutant.
    cleanupCrashProbe();
    writeCrashProbe();
    try {
      const result = runScript(
        [`--filter=${CRASH_FILE_NAME}`],
        {},
        30000,
      );
      // Crashed suite = failed (not dropped) → UNION GUARD exits 1.
      expect(result.exitCode).toBe(1);
      expect(result.stdout).toContain("SUMMARY");
      expect(result.stdout).toContain("FAIL");
    } finally {
      cleanupCrashProbe();
    }
  });
});

describe("UNION GUARD missing-suite path (T24 → DI-02)", () => {
  // History: T24's version of this test asserted the guard's SOURCE TEXT
  // (grep for "UNION GUARD FAIL" in the runner) because runSuite always
  // resolves, so the missing branch was unreachable end-to-end — a method
  // test is not a call-site test, and deleting the branch's `return 1`
  // was invisible to every suite (lesson L-001). DI-02 added the
  // _PARALLEL_DROP_RESULT seam: the runner drops one assembled result
  // pre-guard, making the wiring — exit 1 plus the FAIL line naming the
  // id — observable behavior instead of quoted text.
  const DROP_FILE_NAME = "__zzz_di02_drop_probe.test.ts";
  const DROP_FILE_PATH = path.join(CORE_TESTS_ROOT, DROP_FILE_NAME);
  // Classifier: process.env assignment → "process-global state" → its own
  // suite; id = `${reason}:${path relative to packages/core}`.
  const DROP_SUITE_ID = `process-global state:src/__tests__/${DROP_FILE_NAME}`;

  function writePassingProbe(): void {
    writeFileSync(DROP_FILE_PATH, [
      `// Auto-generated by run-tests-parallel.test.ts — do NOT commit.`,
      `// Exists only during the DI-02 drop probe, then is removed.`,
      `process.env.__DI02_DROP_PROBE = "1";`,
      `import { test, expect } from "bun:test";`,
      `test("di02 drop probe passes", () => { expect(1).toBe(1); });`,
      ``,
    ].join("\n"));
  }

  function cleanupPassingProbe(): void {
    try {
      if (existsSync(DROP_FILE_PATH)) rmSync(DROP_FILE_PATH, { force: true });
    } catch {
      // best-effort
    }
  }

  test("control: probe passes and the guard stays quiet (exit 0, seam unset)", () => {
    cleanupPassingProbe();
    writePassingProbe();
    try {
      const result = runScript([`--filter=${DROP_FILE_NAME}`], {}, 30000);
      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("SUMMARY");
      expect(result.stderr).not.toContain("UNION GUARD FAIL");
    } finally {
      cleanupPassingProbe();
    }
  });

  test("a listed suite whose result is dropped → UNION GUARD FAIL naming it (exit 1)", () => {
    cleanupPassingProbe();
    writePassingProbe();
    try {
      const result = runScript(
        [`--filter=${DROP_FILE_NAME}`],
        { _PARALLEL_DROP_RESULT: DROP_SUITE_ID },
        30000,
      );
      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("UNION GUARD FAIL");
      expect(result.stderr).toContain(DROP_SUITE_ID);
    } finally {
      cleanupPassingProbe();
    }
  });

  test("an unknown drop id is a no-op (exit 0)", () => {
    cleanupPassingProbe();
    writePassingProbe();
    try {
      const result = runScript(
        [`--filter=${DROP_FILE_NAME}`],
        { _PARALLEL_DROP_RESULT: "no-such-reason:no/such/file.test.ts" },
        30000,
      );
      expect(result.exitCode).toBe(0);
      expect(result.stderr).not.toContain("UNION GUARD FAIL");
    } finally {
      cleanupPassingProbe();
    }
  });

  test("empty filter (0 suites) does not trigger the missing-suite guard", () => {
    const empty = runScript(["--filter=ZZZ_NEVER_MATCHES_anything_xyz"]);
    expect(empty.exitCode).toBe(0);
  });
});